
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CourseHasCategory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model CourseHasCategory
 * 
 */
export type CourseHasCategoryModel = runtime.Types.Result.DefaultSelection<Prisma.$CourseHasCategoryPayload>

export type AggregateCourseHasCategory = {
  _count: CourseHasCategoryCountAggregateOutputType | null
  _min: CourseHasCategoryMinAggregateOutputType | null
  _max: CourseHasCategoryMaxAggregateOutputType | null
}

export type CourseHasCategoryMinAggregateOutputType = {
  courseId: string | null
  categoryId: string | null
}

export type CourseHasCategoryMaxAggregateOutputType = {
  courseId: string | null
  categoryId: string | null
}

export type CourseHasCategoryCountAggregateOutputType = {
  courseId: number
  categoryId: number
  _all: number
}


export type CourseHasCategoryMinAggregateInputType = {
  courseId?: true
  categoryId?: true
}

export type CourseHasCategoryMaxAggregateInputType = {
  courseId?: true
  categoryId?: true
}

export type CourseHasCategoryCountAggregateInputType = {
  courseId?: true
  categoryId?: true
  _all?: true
}

export type CourseHasCategoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CourseHasCategory to aggregate.
   */
  where?: Prisma.CourseHasCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CourseHasCategories to fetch.
   */
  orderBy?: Prisma.CourseHasCategoryOrderByWithRelationInput | Prisma.CourseHasCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CourseHasCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CourseHasCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CourseHasCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CourseHasCategories
  **/
  _count?: true | CourseHasCategoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CourseHasCategoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CourseHasCategoryMaxAggregateInputType
}

export type GetCourseHasCategoryAggregateType<T extends CourseHasCategoryAggregateArgs> = {
      [P in keyof T & keyof AggregateCourseHasCategory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCourseHasCategory[P]>
    : Prisma.GetScalarType<T[P], AggregateCourseHasCategory[P]>
}




export type CourseHasCategoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CourseHasCategoryWhereInput
  orderBy?: Prisma.CourseHasCategoryOrderByWithAggregationInput | Prisma.CourseHasCategoryOrderByWithAggregationInput[]
  by: Prisma.CourseHasCategoryScalarFieldEnum[] | Prisma.CourseHasCategoryScalarFieldEnum
  having?: Prisma.CourseHasCategoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CourseHasCategoryCountAggregateInputType | true
  _min?: CourseHasCategoryMinAggregateInputType
  _max?: CourseHasCategoryMaxAggregateInputType
}

export type CourseHasCategoryGroupByOutputType = {
  courseId: string
  categoryId: string
  _count: CourseHasCategoryCountAggregateOutputType | null
  _min: CourseHasCategoryMinAggregateOutputType | null
  _max: CourseHasCategoryMaxAggregateOutputType | null
}

type GetCourseHasCategoryGroupByPayload<T extends CourseHasCategoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CourseHasCategoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CourseHasCategoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CourseHasCategoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CourseHasCategoryGroupByOutputType[P]>
      }
    >
  >



export type CourseHasCategoryWhereInput = {
  AND?: Prisma.CourseHasCategoryWhereInput | Prisma.CourseHasCategoryWhereInput[]
  OR?: Prisma.CourseHasCategoryWhereInput[]
  NOT?: Prisma.CourseHasCategoryWhereInput | Prisma.CourseHasCategoryWhereInput[]
  courseId?: Prisma.StringFilter<"CourseHasCategory"> | string
  categoryId?: Prisma.StringFilter<"CourseHasCategory"> | string
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
}

export type CourseHasCategoryOrderByWithRelationInput = {
  courseId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  course?: Prisma.CourseOrderByWithRelationInput
  category?: Prisma.CategoryOrderByWithRelationInput
}

export type CourseHasCategoryWhereUniqueInput = Prisma.AtLeast<{
  courseId_categoryId?: Prisma.CourseHasCategoryCourseIdCategoryIdCompoundUniqueInput
  AND?: Prisma.CourseHasCategoryWhereInput | Prisma.CourseHasCategoryWhereInput[]
  OR?: Prisma.CourseHasCategoryWhereInput[]
  NOT?: Prisma.CourseHasCategoryWhereInput | Prisma.CourseHasCategoryWhereInput[]
  courseId?: Prisma.StringFilter<"CourseHasCategory"> | string
  categoryId?: Prisma.StringFilter<"CourseHasCategory"> | string
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
}, "courseId_categoryId">

export type CourseHasCategoryOrderByWithAggregationInput = {
  courseId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  _count?: Prisma.CourseHasCategoryCountOrderByAggregateInput
  _max?: Prisma.CourseHasCategoryMaxOrderByAggregateInput
  _min?: Prisma.CourseHasCategoryMinOrderByAggregateInput
}

export type CourseHasCategoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.CourseHasCategoryScalarWhereWithAggregatesInput | Prisma.CourseHasCategoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.CourseHasCategoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CourseHasCategoryScalarWhereWithAggregatesInput | Prisma.CourseHasCategoryScalarWhereWithAggregatesInput[]
  courseId?: Prisma.StringWithAggregatesFilter<"CourseHasCategory"> | string
  categoryId?: Prisma.StringWithAggregatesFilter<"CourseHasCategory"> | string
}

export type CourseHasCategoryCreateInput = {
  course: Prisma.CourseCreateNestedOneWithoutCategoriesInput
  category: Prisma.CategoryCreateNestedOneWithoutCoursesInput
}

export type CourseHasCategoryUncheckedCreateInput = {
  courseId: string
  categoryId: string
}

export type CourseHasCategoryUpdateInput = {
  course?: Prisma.CourseUpdateOneRequiredWithoutCategoriesNestedInput
  category?: Prisma.CategoryUpdateOneRequiredWithoutCoursesNestedInput
}

export type CourseHasCategoryUncheckedUpdateInput = {
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CourseHasCategoryCreateManyInput = {
  courseId: string
  categoryId: string
}

export type CourseHasCategoryUpdateManyMutationInput = {

}

export type CourseHasCategoryUncheckedUpdateManyInput = {
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CourseHasCategoryListRelationFilter = {
  every?: Prisma.CourseHasCategoryWhereInput
  some?: Prisma.CourseHasCategoryWhereInput
  none?: Prisma.CourseHasCategoryWhereInput
}

export type CourseHasCategoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CourseHasCategoryCourseIdCategoryIdCompoundUniqueInput = {
  courseId: string
  categoryId: string
}

export type CourseHasCategoryCountOrderByAggregateInput = {
  courseId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type CourseHasCategoryMaxOrderByAggregateInput = {
  courseId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type CourseHasCategoryMinOrderByAggregateInput = {
  courseId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type CourseHasCategoryCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCourseInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCourseInput> | Prisma.CourseHasCategoryCreateWithoutCourseInput[] | Prisma.CourseHasCategoryUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.CourseHasCategoryCreateOrConnectWithoutCourseInput | Prisma.CourseHasCategoryCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.CourseHasCategoryCreateManyCourseInputEnvelope
  connect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
}

export type CourseHasCategoryUncheckedCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCourseInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCourseInput> | Prisma.CourseHasCategoryCreateWithoutCourseInput[] | Prisma.CourseHasCategoryUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.CourseHasCategoryCreateOrConnectWithoutCourseInput | Prisma.CourseHasCategoryCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.CourseHasCategoryCreateManyCourseInputEnvelope
  connect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
}

export type CourseHasCategoryUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCourseInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCourseInput> | Prisma.CourseHasCategoryCreateWithoutCourseInput[] | Prisma.CourseHasCategoryUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.CourseHasCategoryCreateOrConnectWithoutCourseInput | Prisma.CourseHasCategoryCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.CourseHasCategoryUpsertWithWhereUniqueWithoutCourseInput | Prisma.CourseHasCategoryUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.CourseHasCategoryCreateManyCourseInputEnvelope
  set?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  disconnect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  delete?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  connect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  update?: Prisma.CourseHasCategoryUpdateWithWhereUniqueWithoutCourseInput | Prisma.CourseHasCategoryUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.CourseHasCategoryUpdateManyWithWhereWithoutCourseInput | Prisma.CourseHasCategoryUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.CourseHasCategoryScalarWhereInput | Prisma.CourseHasCategoryScalarWhereInput[]
}

export type CourseHasCategoryUncheckedUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCourseInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCourseInput> | Prisma.CourseHasCategoryCreateWithoutCourseInput[] | Prisma.CourseHasCategoryUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.CourseHasCategoryCreateOrConnectWithoutCourseInput | Prisma.CourseHasCategoryCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.CourseHasCategoryUpsertWithWhereUniqueWithoutCourseInput | Prisma.CourseHasCategoryUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.CourseHasCategoryCreateManyCourseInputEnvelope
  set?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  disconnect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  delete?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  connect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  update?: Prisma.CourseHasCategoryUpdateWithWhereUniqueWithoutCourseInput | Prisma.CourseHasCategoryUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.CourseHasCategoryUpdateManyWithWhereWithoutCourseInput | Prisma.CourseHasCategoryUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.CourseHasCategoryScalarWhereInput | Prisma.CourseHasCategoryScalarWhereInput[]
}

export type CourseHasCategoryCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCategoryInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCategoryInput> | Prisma.CourseHasCategoryCreateWithoutCategoryInput[] | Prisma.CourseHasCategoryUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.CourseHasCategoryCreateOrConnectWithoutCategoryInput | Prisma.CourseHasCategoryCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.CourseHasCategoryCreateManyCategoryInputEnvelope
  connect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
}

export type CourseHasCategoryUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCategoryInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCategoryInput> | Prisma.CourseHasCategoryCreateWithoutCategoryInput[] | Prisma.CourseHasCategoryUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.CourseHasCategoryCreateOrConnectWithoutCategoryInput | Prisma.CourseHasCategoryCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.CourseHasCategoryCreateManyCategoryInputEnvelope
  connect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
}

export type CourseHasCategoryUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCategoryInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCategoryInput> | Prisma.CourseHasCategoryCreateWithoutCategoryInput[] | Prisma.CourseHasCategoryUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.CourseHasCategoryCreateOrConnectWithoutCategoryInput | Prisma.CourseHasCategoryCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.CourseHasCategoryUpsertWithWhereUniqueWithoutCategoryInput | Prisma.CourseHasCategoryUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.CourseHasCategoryCreateManyCategoryInputEnvelope
  set?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  disconnect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  delete?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  connect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  update?: Prisma.CourseHasCategoryUpdateWithWhereUniqueWithoutCategoryInput | Prisma.CourseHasCategoryUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.CourseHasCategoryUpdateManyWithWhereWithoutCategoryInput | Prisma.CourseHasCategoryUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.CourseHasCategoryScalarWhereInput | Prisma.CourseHasCategoryScalarWhereInput[]
}

export type CourseHasCategoryUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCategoryInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCategoryInput> | Prisma.CourseHasCategoryCreateWithoutCategoryInput[] | Prisma.CourseHasCategoryUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.CourseHasCategoryCreateOrConnectWithoutCategoryInput | Prisma.CourseHasCategoryCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.CourseHasCategoryUpsertWithWhereUniqueWithoutCategoryInput | Prisma.CourseHasCategoryUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.CourseHasCategoryCreateManyCategoryInputEnvelope
  set?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  disconnect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  delete?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  connect?: Prisma.CourseHasCategoryWhereUniqueInput | Prisma.CourseHasCategoryWhereUniqueInput[]
  update?: Prisma.CourseHasCategoryUpdateWithWhereUniqueWithoutCategoryInput | Prisma.CourseHasCategoryUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.CourseHasCategoryUpdateManyWithWhereWithoutCategoryInput | Prisma.CourseHasCategoryUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.CourseHasCategoryScalarWhereInput | Prisma.CourseHasCategoryScalarWhereInput[]
}

export type CourseHasCategoryCreateWithoutCourseInput = {
  category: Prisma.CategoryCreateNestedOneWithoutCoursesInput
}

export type CourseHasCategoryUncheckedCreateWithoutCourseInput = {
  categoryId: string
}

export type CourseHasCategoryCreateOrConnectWithoutCourseInput = {
  where: Prisma.CourseHasCategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCourseInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCourseInput>
}

export type CourseHasCategoryCreateManyCourseInputEnvelope = {
  data: Prisma.CourseHasCategoryCreateManyCourseInput | Prisma.CourseHasCategoryCreateManyCourseInput[]
  skipDuplicates?: boolean
}

export type CourseHasCategoryUpsertWithWhereUniqueWithoutCourseInput = {
  where: Prisma.CourseHasCategoryWhereUniqueInput
  update: Prisma.XOR<Prisma.CourseHasCategoryUpdateWithoutCourseInput, Prisma.CourseHasCategoryUncheckedUpdateWithoutCourseInput>
  create: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCourseInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCourseInput>
}

export type CourseHasCategoryUpdateWithWhereUniqueWithoutCourseInput = {
  where: Prisma.CourseHasCategoryWhereUniqueInput
  data: Prisma.XOR<Prisma.CourseHasCategoryUpdateWithoutCourseInput, Prisma.CourseHasCategoryUncheckedUpdateWithoutCourseInput>
}

export type CourseHasCategoryUpdateManyWithWhereWithoutCourseInput = {
  where: Prisma.CourseHasCategoryScalarWhereInput
  data: Prisma.XOR<Prisma.CourseHasCategoryUpdateManyMutationInput, Prisma.CourseHasCategoryUncheckedUpdateManyWithoutCourseInput>
}

export type CourseHasCategoryScalarWhereInput = {
  AND?: Prisma.CourseHasCategoryScalarWhereInput | Prisma.CourseHasCategoryScalarWhereInput[]
  OR?: Prisma.CourseHasCategoryScalarWhereInput[]
  NOT?: Prisma.CourseHasCategoryScalarWhereInput | Prisma.CourseHasCategoryScalarWhereInput[]
  courseId?: Prisma.StringFilter<"CourseHasCategory"> | string
  categoryId?: Prisma.StringFilter<"CourseHasCategory"> | string
}

export type CourseHasCategoryCreateWithoutCategoryInput = {
  course: Prisma.CourseCreateNestedOneWithoutCategoriesInput
}

export type CourseHasCategoryUncheckedCreateWithoutCategoryInput = {
  courseId: string
}

export type CourseHasCategoryCreateOrConnectWithoutCategoryInput = {
  where: Prisma.CourseHasCategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCategoryInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCategoryInput>
}

export type CourseHasCategoryCreateManyCategoryInputEnvelope = {
  data: Prisma.CourseHasCategoryCreateManyCategoryInput | Prisma.CourseHasCategoryCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type CourseHasCategoryUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.CourseHasCategoryWhereUniqueInput
  update: Prisma.XOR<Prisma.CourseHasCategoryUpdateWithoutCategoryInput, Prisma.CourseHasCategoryUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.CourseHasCategoryCreateWithoutCategoryInput, Prisma.CourseHasCategoryUncheckedCreateWithoutCategoryInput>
}

export type CourseHasCategoryUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.CourseHasCategoryWhereUniqueInput
  data: Prisma.XOR<Prisma.CourseHasCategoryUpdateWithoutCategoryInput, Prisma.CourseHasCategoryUncheckedUpdateWithoutCategoryInput>
}

export type CourseHasCategoryUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.CourseHasCategoryScalarWhereInput
  data: Prisma.XOR<Prisma.CourseHasCategoryUpdateManyMutationInput, Prisma.CourseHasCategoryUncheckedUpdateManyWithoutCategoryInput>
}

export type CourseHasCategoryCreateManyCourseInput = {
  categoryId: string
}

export type CourseHasCategoryUpdateWithoutCourseInput = {
  category?: Prisma.CategoryUpdateOneRequiredWithoutCoursesNestedInput
}

export type CourseHasCategoryUncheckedUpdateWithoutCourseInput = {
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CourseHasCategoryUncheckedUpdateManyWithoutCourseInput = {
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CourseHasCategoryCreateManyCategoryInput = {
  courseId: string
}

export type CourseHasCategoryUpdateWithoutCategoryInput = {
  course?: Prisma.CourseUpdateOneRequiredWithoutCategoriesNestedInput
}

export type CourseHasCategoryUncheckedUpdateWithoutCategoryInput = {
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CourseHasCategoryUncheckedUpdateManyWithoutCategoryInput = {
  courseId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type CourseHasCategorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  courseId?: boolean
  categoryId?: boolean
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["courseHasCategory"]>

export type CourseHasCategorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  courseId?: boolean
  categoryId?: boolean
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["courseHasCategory"]>

export type CourseHasCategorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  courseId?: boolean
  categoryId?: boolean
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["courseHasCategory"]>

export type CourseHasCategorySelectScalar = {
  courseId?: boolean
  categoryId?: boolean
}

export type CourseHasCategoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"courseId" | "categoryId", ExtArgs["result"]["courseHasCategory"]>
export type CourseHasCategoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}
export type CourseHasCategoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}
export type CourseHasCategoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}

export type $CourseHasCategoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CourseHasCategory"
  objects: {
    course: Prisma.$CoursePayload<ExtArgs>
    category: Prisma.$CategoryPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    courseId: string
    categoryId: string
  }, ExtArgs["result"]["courseHasCategory"]>
  composites: {}
}

export type CourseHasCategoryGetPayload<S extends boolean | null | undefined | CourseHasCategoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload, S>

export type CourseHasCategoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CourseHasCategoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CourseHasCategoryCountAggregateInputType | true
  }

export interface CourseHasCategoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CourseHasCategory'], meta: { name: 'CourseHasCategory' } }
  /**
   * Find zero or one CourseHasCategory that matches the filter.
   * @param {CourseHasCategoryFindUniqueArgs} args - Arguments to find a CourseHasCategory
   * @example
   * // Get one CourseHasCategory
   * const courseHasCategory = await prisma.courseHasCategory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CourseHasCategoryFindUniqueArgs>(args: Prisma.SelectSubset<T, CourseHasCategoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CourseHasCategoryClient<runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CourseHasCategory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CourseHasCategoryFindUniqueOrThrowArgs} args - Arguments to find a CourseHasCategory
   * @example
   * // Get one CourseHasCategory
   * const courseHasCategory = await prisma.courseHasCategory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CourseHasCategoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CourseHasCategoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CourseHasCategoryClient<runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CourseHasCategory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseHasCategoryFindFirstArgs} args - Arguments to find a CourseHasCategory
   * @example
   * // Get one CourseHasCategory
   * const courseHasCategory = await prisma.courseHasCategory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CourseHasCategoryFindFirstArgs>(args?: Prisma.SelectSubset<T, CourseHasCategoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__CourseHasCategoryClient<runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CourseHasCategory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseHasCategoryFindFirstOrThrowArgs} args - Arguments to find a CourseHasCategory
   * @example
   * // Get one CourseHasCategory
   * const courseHasCategory = await prisma.courseHasCategory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CourseHasCategoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CourseHasCategoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CourseHasCategoryClient<runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CourseHasCategories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseHasCategoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CourseHasCategories
   * const courseHasCategories = await prisma.courseHasCategory.findMany()
   * 
   * // Get first 10 CourseHasCategories
   * const courseHasCategories = await prisma.courseHasCategory.findMany({ take: 10 })
   * 
   * // Only select the `courseId`
   * const courseHasCategoryWithCourseIdOnly = await prisma.courseHasCategory.findMany({ select: { courseId: true } })
   * 
   */
  findMany<T extends CourseHasCategoryFindManyArgs>(args?: Prisma.SelectSubset<T, CourseHasCategoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CourseHasCategory.
   * @param {CourseHasCategoryCreateArgs} args - Arguments to create a CourseHasCategory.
   * @example
   * // Create one CourseHasCategory
   * const CourseHasCategory = await prisma.courseHasCategory.create({
   *   data: {
   *     // ... data to create a CourseHasCategory
   *   }
   * })
   * 
   */
  create<T extends CourseHasCategoryCreateArgs>(args: Prisma.SelectSubset<T, CourseHasCategoryCreateArgs<ExtArgs>>): Prisma.Prisma__CourseHasCategoryClient<runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CourseHasCategories.
   * @param {CourseHasCategoryCreateManyArgs} args - Arguments to create many CourseHasCategories.
   * @example
   * // Create many CourseHasCategories
   * const courseHasCategory = await prisma.courseHasCategory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CourseHasCategoryCreateManyArgs>(args?: Prisma.SelectSubset<T, CourseHasCategoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CourseHasCategories and returns the data saved in the database.
   * @param {CourseHasCategoryCreateManyAndReturnArgs} args - Arguments to create many CourseHasCategories.
   * @example
   * // Create many CourseHasCategories
   * const courseHasCategory = await prisma.courseHasCategory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CourseHasCategories and only return the `courseId`
   * const courseHasCategoryWithCourseIdOnly = await prisma.courseHasCategory.createManyAndReturn({
   *   select: { courseId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CourseHasCategoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CourseHasCategoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CourseHasCategory.
   * @param {CourseHasCategoryDeleteArgs} args - Arguments to delete one CourseHasCategory.
   * @example
   * // Delete one CourseHasCategory
   * const CourseHasCategory = await prisma.courseHasCategory.delete({
   *   where: {
   *     // ... filter to delete one CourseHasCategory
   *   }
   * })
   * 
   */
  delete<T extends CourseHasCategoryDeleteArgs>(args: Prisma.SelectSubset<T, CourseHasCategoryDeleteArgs<ExtArgs>>): Prisma.Prisma__CourseHasCategoryClient<runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CourseHasCategory.
   * @param {CourseHasCategoryUpdateArgs} args - Arguments to update one CourseHasCategory.
   * @example
   * // Update one CourseHasCategory
   * const courseHasCategory = await prisma.courseHasCategory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CourseHasCategoryUpdateArgs>(args: Prisma.SelectSubset<T, CourseHasCategoryUpdateArgs<ExtArgs>>): Prisma.Prisma__CourseHasCategoryClient<runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CourseHasCategories.
   * @param {CourseHasCategoryDeleteManyArgs} args - Arguments to filter CourseHasCategories to delete.
   * @example
   * // Delete a few CourseHasCategories
   * const { count } = await prisma.courseHasCategory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CourseHasCategoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, CourseHasCategoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CourseHasCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseHasCategoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CourseHasCategories
   * const courseHasCategory = await prisma.courseHasCategory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CourseHasCategoryUpdateManyArgs>(args: Prisma.SelectSubset<T, CourseHasCategoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CourseHasCategories and returns the data updated in the database.
   * @param {CourseHasCategoryUpdateManyAndReturnArgs} args - Arguments to update many CourseHasCategories.
   * @example
   * // Update many CourseHasCategories
   * const courseHasCategory = await prisma.courseHasCategory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CourseHasCategories and only return the `courseId`
   * const courseHasCategoryWithCourseIdOnly = await prisma.courseHasCategory.updateManyAndReturn({
   *   select: { courseId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CourseHasCategoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CourseHasCategoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CourseHasCategory.
   * @param {CourseHasCategoryUpsertArgs} args - Arguments to update or create a CourseHasCategory.
   * @example
   * // Update or create a CourseHasCategory
   * const courseHasCategory = await prisma.courseHasCategory.upsert({
   *   create: {
   *     // ... data to create a CourseHasCategory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CourseHasCategory we want to update
   *   }
   * })
   */
  upsert<T extends CourseHasCategoryUpsertArgs>(args: Prisma.SelectSubset<T, CourseHasCategoryUpsertArgs<ExtArgs>>): Prisma.Prisma__CourseHasCategoryClient<runtime.Types.Result.GetResult<Prisma.$CourseHasCategoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CourseHasCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseHasCategoryCountArgs} args - Arguments to filter CourseHasCategories to count.
   * @example
   * // Count the number of CourseHasCategories
   * const count = await prisma.courseHasCategory.count({
   *   where: {
   *     // ... the filter for the CourseHasCategories we want to count
   *   }
   * })
  **/
  count<T extends CourseHasCategoryCountArgs>(
    args?: Prisma.Subset<T, CourseHasCategoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CourseHasCategoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CourseHasCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseHasCategoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CourseHasCategoryAggregateArgs>(args: Prisma.Subset<T, CourseHasCategoryAggregateArgs>): Prisma.PrismaPromise<GetCourseHasCategoryAggregateType<T>>

  /**
   * Group by CourseHasCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseHasCategoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CourseHasCategoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CourseHasCategoryGroupByArgs['orderBy'] }
      : { orderBy?: CourseHasCategoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CourseHasCategoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCourseHasCategoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CourseHasCategory model
 */
readonly fields: CourseHasCategoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CourseHasCategory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CourseHasCategoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  course<T extends Prisma.CourseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CourseDefaultArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  category<T extends Prisma.CategoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CategoryDefaultArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CourseHasCategory model
 */
export interface CourseHasCategoryFieldRefs {
  readonly courseId: Prisma.FieldRef<"CourseHasCategory", 'String'>
  readonly categoryId: Prisma.FieldRef<"CourseHasCategory", 'String'>
}
    

// Custom InputTypes
/**
 * CourseHasCategory findUnique
 */
export type CourseHasCategoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryInclude<ExtArgs> | null
  /**
   * Filter, which CourseHasCategory to fetch.
   */
  where: Prisma.CourseHasCategoryWhereUniqueInput
}

/**
 * CourseHasCategory findUniqueOrThrow
 */
export type CourseHasCategoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryInclude<ExtArgs> | null
  /**
   * Filter, which CourseHasCategory to fetch.
   */
  where: Prisma.CourseHasCategoryWhereUniqueInput
}

/**
 * CourseHasCategory findFirst
 */
export type CourseHasCategoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryInclude<ExtArgs> | null
  /**
   * Filter, which CourseHasCategory to fetch.
   */
  where?: Prisma.CourseHasCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CourseHasCategories to fetch.
   */
  orderBy?: Prisma.CourseHasCategoryOrderByWithRelationInput | Prisma.CourseHasCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CourseHasCategories.
   */
  cursor?: Prisma.CourseHasCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CourseHasCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CourseHasCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CourseHasCategories.
   */
  distinct?: Prisma.CourseHasCategoryScalarFieldEnum | Prisma.CourseHasCategoryScalarFieldEnum[]
}

/**
 * CourseHasCategory findFirstOrThrow
 */
export type CourseHasCategoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryInclude<ExtArgs> | null
  /**
   * Filter, which CourseHasCategory to fetch.
   */
  where?: Prisma.CourseHasCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CourseHasCategories to fetch.
   */
  orderBy?: Prisma.CourseHasCategoryOrderByWithRelationInput | Prisma.CourseHasCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CourseHasCategories.
   */
  cursor?: Prisma.CourseHasCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CourseHasCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CourseHasCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CourseHasCategories.
   */
  distinct?: Prisma.CourseHasCategoryScalarFieldEnum | Prisma.CourseHasCategoryScalarFieldEnum[]
}

/**
 * CourseHasCategory findMany
 */
export type CourseHasCategoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryInclude<ExtArgs> | null
  /**
   * Filter, which CourseHasCategories to fetch.
   */
  where?: Prisma.CourseHasCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CourseHasCategories to fetch.
   */
  orderBy?: Prisma.CourseHasCategoryOrderByWithRelationInput | Prisma.CourseHasCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CourseHasCategories.
   */
  cursor?: Prisma.CourseHasCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CourseHasCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CourseHasCategories.
   */
  skip?: number
  distinct?: Prisma.CourseHasCategoryScalarFieldEnum | Prisma.CourseHasCategoryScalarFieldEnum[]
}

/**
 * CourseHasCategory create
 */
export type CourseHasCategoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryInclude<ExtArgs> | null
  /**
   * The data needed to create a CourseHasCategory.
   */
  data: Prisma.XOR<Prisma.CourseHasCategoryCreateInput, Prisma.CourseHasCategoryUncheckedCreateInput>
}

/**
 * CourseHasCategory createMany
 */
export type CourseHasCategoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CourseHasCategories.
   */
  data: Prisma.CourseHasCategoryCreateManyInput | Prisma.CourseHasCategoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CourseHasCategory createManyAndReturn
 */
export type CourseHasCategoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * The data used to create many CourseHasCategories.
   */
  data: Prisma.CourseHasCategoryCreateManyInput | Prisma.CourseHasCategoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CourseHasCategory update
 */
export type CourseHasCategoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryInclude<ExtArgs> | null
  /**
   * The data needed to update a CourseHasCategory.
   */
  data: Prisma.XOR<Prisma.CourseHasCategoryUpdateInput, Prisma.CourseHasCategoryUncheckedUpdateInput>
  /**
   * Choose, which CourseHasCategory to update.
   */
  where: Prisma.CourseHasCategoryWhereUniqueInput
}

/**
 * CourseHasCategory updateMany
 */
export type CourseHasCategoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CourseHasCategories.
   */
  data: Prisma.XOR<Prisma.CourseHasCategoryUpdateManyMutationInput, Prisma.CourseHasCategoryUncheckedUpdateManyInput>
  /**
   * Filter which CourseHasCategories to update
   */
  where?: Prisma.CourseHasCategoryWhereInput
  /**
   * Limit how many CourseHasCategories to update.
   */
  limit?: number
}

/**
 * CourseHasCategory updateManyAndReturn
 */
export type CourseHasCategoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * The data used to update CourseHasCategories.
   */
  data: Prisma.XOR<Prisma.CourseHasCategoryUpdateManyMutationInput, Prisma.CourseHasCategoryUncheckedUpdateManyInput>
  /**
   * Filter which CourseHasCategories to update
   */
  where?: Prisma.CourseHasCategoryWhereInput
  /**
   * Limit how many CourseHasCategories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CourseHasCategory upsert
 */
export type CourseHasCategoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryInclude<ExtArgs> | null
  /**
   * The filter to search for the CourseHasCategory to update in case it exists.
   */
  where: Prisma.CourseHasCategoryWhereUniqueInput
  /**
   * In case the CourseHasCategory found by the `where` argument doesn't exist, create a new CourseHasCategory with this data.
   */
  create: Prisma.XOR<Prisma.CourseHasCategoryCreateInput, Prisma.CourseHasCategoryUncheckedCreateInput>
  /**
   * In case the CourseHasCategory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CourseHasCategoryUpdateInput, Prisma.CourseHasCategoryUncheckedUpdateInput>
}

/**
 * CourseHasCategory delete
 */
export type CourseHasCategoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryInclude<ExtArgs> | null
  /**
   * Filter which CourseHasCategory to delete.
   */
  where: Prisma.CourseHasCategoryWhereUniqueInput
}

/**
 * CourseHasCategory deleteMany
 */
export type CourseHasCategoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CourseHasCategories to delete
   */
  where?: Prisma.CourseHasCategoryWhereInput
  /**
   * Limit how many CourseHasCategories to delete.
   */
  limit?: number
}

/**
 * CourseHasCategory without action
 */
export type CourseHasCategoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseHasCategory
   */
  select?: Prisma.CourseHasCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseHasCategory
   */
  omit?: Prisma.CourseHasCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseHasCategoryInclude<ExtArgs> | null
}
